# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "../www", "/var/www", 
      nfs: true
  config.vm.synced_folder "../vagrant", "/vagrant", 
      nfs: true

  config.vm.network "private_network", ip: "192.168.33.13"

  config.vm.provider "virtualbox" do |v|
      v.name = "LEMP Vagrant"
      v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.provision "shell", path: "provision.sh"

end
